### ISSUE TITLE
Add Dependabot Support

### ISSUE THREAD

**Issue by beanbeanjuice** [UC-Davis-molecular-computing/scadnano#1025]
Dependabot can automatically create pull requests for dependencies for a specific branch. In this case, dependabot can automatically create pull requests for the `dev` branch, whenever there is an update to one of the dependencies.

```YAML
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/" # Directory of pubspec.yaml
    target-branch: "dev"
    schedule:
      interval: "weekly" # daily, weekly, monthly
```
