### ISSUE TITLE
migrate to Dart null safety mode

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#419]
Dart null safety is coming soon. It will have stronger checks on types than older versions, in particular:

https://codewithandrea.com/articles/2020-06-22-implicit-downcast-no-longer-allowed/#disabling-implicit-downcasts-in-analysis_optionsyaml

We can enable those checks to be reported by the static analyzer in Dart 2.8, in analysis_options.yaml, by setting these two values to false:

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

Do this and then deal with the avalanche of type errors.

One annoying thing is that is requires every function/method to have a return type, even though I've been leaving it off for functions with a `void` return type. So there will be several hundred of these to correct.
