### ISSUE TITLE
turn on strict analysis

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#991]
analysis_options.yaml has these lines:

```yaml
analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
```

Set them both to true and deal with the avalanche of warnings/errors it produces. This may be a good idea to do prior to tackling #990 to upgrade to Dart 3.
